VDS-334: Create/update customer segment rule
VirtoCommerce/vc-module-demo-customer-segments pull request #12
Opened 2020-12-07 16:03 UTC by trueboroda

Without indexation.

2020-12-08 09:52 UTC, pushnitsa requested changes

2020-12-08 09:52 UTC, pushnitsa commented on src/VirtoCommerce.DemoCustomerSegmentsModule.Web/Scripts/blades/customerSegment-detail.js
> +        blade.refresh = function (parentRefresh) {
Make all functions arrowed if it is possible for unifying

2020-12-08 09:52 UTC, pushnitsa commented on src/VirtoCommerce.DemoCustomerSegmentsModule.Web/Scripts/blades/customerSegment-detail.tpl.html
> +                            <ui-select ng-model="blade.currentEntity.userGroup">
Add required attribute

2020-12-08 09:52 UTC, pushnitsa commented on src/VirtoCommerce.DemoCustomerSegmentsModule.Web/Scripts/blades/customerSegment-list.js
> +                    $scope.hasMore = data.results.length === $scope.pageSettings.itemsPerPageCount;
data.results && data.results.length

2020-12-08 09:52 UTC, pushnitsa commented on src/VirtoCommerce.DemoCustomerSegmentsModule.Web/Scripts/blades/customerSegment-list.js
> +            blade.refresh = function () {
Use arrow function as much as you can.

2020-12-08 09:52 UTC, pushnitsa commented on src/VirtoCommerce.DemoCustomerSegmentsModule.Web/Scripts/resources/customerSegments.js
> +        update: { method: 'POST', isArray: true },
save

2020-12-08 14:14 UTC, pushnitsa approved these changes

2020-12-09 15:10 UTC, asvishnyakov approved these changes

2020-12-09 15:10 UTC, merged