Move customer segments to separate module
VirtoCommerce/vc-module-demo-customer-segments pull request #2
Opened 2020-12-02 15:20 UTC by trueboroda

2020-12-02 15:23 UTC, mvktsk commented
Review task https://virtocommerce.atlassian.net/browse/VP-6301 has been created

2020-12-03 06:52 UTC, pushnitsa requested changes

2020-12-03 06:52 UTC, pushnitsa commented on src/VirtoCommerce.DemoCustomerSegmentsModule.Web/module.manifest
> +        <author>asvishnyakov</author>
Please use full developer names

2020-12-03 06:52 UTC, pushnitsa commented on src/VirtoCommerce.DemoCustomerSegmentsModule.Web/module.manifest
> +        <dependency id="VirtoCommerce.Core" version="3.0.0" />
Where is marketing module dependency?

2020-12-03 06:52 UTC, pushnitsa commented on src/VirtoCommerce.DemoCustomerSegmentsModule.Web/Scripts/resources/customerSegments.js
> +        preview: { method: 'POST', url: 'api/demo/customersegments/preview', isArray: true }
We don't have this endpoint anymore, isn't it?

2020-12-03 06:52 UTC, pushnitsa commented on src/VirtoCommerce.DemoCustomerSegmentsModule.Web/Scripts/blades/customerSegments-preview.tpl.html
> +</script>
Add empty string in the end of file

2020-12-03 06:52 UTC, pushnitsa commented on src/VirtoCommerce.DemoCustomerSegmentsModule.Web/Module.cs
> +            using (var serviceScope = appBuilder.ApplicationServices.CreateScope())
Union using declarations

2020-12-03 06:52 UTC, pushnitsa commented on src/VirtoCommerce.DemoCustomerSegmentsModule.Web/Controllers/Api/DemoCustomerSegmentController.cs
> +        [Authorize(ModuleConstants.Security.Permissions.Read)]
Should we use here marketing permissions?

2020-12-03 08:29 UTC, asvishnyakov requested changes

2020-12-03 08:29 UTC, asvishnyakov commented on src/VirtoCommerce.DemoCustomerSegmentsModule.Core/VirtoCommerce.DemoCustomerSegmentsModule.Core.csproj
> +    <PackageReference Include="VirtoCommerce.CoreModule.Core" Version="3.8.0" />
Should be 3.7.0

2020-12-03 08:29 UTC, asvishnyakov commented on src/VirtoCommerce.DemoCustomerSegmentsModule.Core/VirtoCommerce.DemoCustomerSegmentsModule.Core.csproj
> +    <PackageReference Include="VirtoCommerce.Platform.Core" Version="3.16.0" />
Should be 3.29.0

2020-12-03 10:13 UTC, asvishnyakov requested changes

2020-12-03 10:13 UTC, asvishnyakov commented on src/VirtoCommerce.DemoCustomerSegmentsModule.Data/VirtoCommerce.DemoCustomerSegmentsModule.Data.csproj
> +    <PackageReference Include="VirtoCommerce.Platform.Data" Version="3.0.0" />
Update versions to used on environment too

2020-12-03 10:32 UTC, asvishnyakov commented on src/VirtoCommerce.DemoCustomerSegmentsModule.Core/VirtoCommerce.DemoCustomerSegmentsModule.Core.csproj
> +    <PackageReference Include="VirtoCommerce.CoreModule.Core" Version="3.8.0" />
Fixed

2020-12-03 10:33 UTC, asvishnyakov approved these changes

2020-12-03 12:29 UTC, pushnitsa submitted a review, later dismissed

2020-12-03 14:05 UTC, ilyawzrd approved these changes

2020-12-03 14:20 UTC, ilyawzrd submitted a review, later dismissed

2020-12-03 14:52 UTC, asvishnyakov approved these changes

2020-12-03 15:22 UTC, ilyawzrd approved these changes

2020-12-03 15:58 UTC, merged