VDS-335: Assign UserGroup to customer segment
VirtoCommerce/vc-module-demo-customer-segments pull request #7
Opened 2020-12-03 16:16 UTC by ilyawzrd

2020-12-04 08:20 UTC, asvishnyakov requested changes
All other changes is OK

2020-12-04 08:20 UTC, asvishnyakov commented on src/VirtoCommerce.DemoCustomerSegmentsModule.Core/Models/DemoCustomerSegment.cs
> +        public string UserGroup { get; set; }
[StringLength(64)]
https://github.com/VirtoCommerce/vc-module-customer/blob/ff7dd139fcbb8a9ead90c988d141d5dadec7cd0e/src/VirtoCommerce.CustomerModule.Data/Model/MemberGroupEntity.cs#L9

2020-12-04 08:21 UTC, asvishnyakov commented on src/VirtoCommerce.DemoCustomerSegmentsModule.Core/Models/DemoCustomerSegment.cs
> +        public string UserGroup { get; set; }
Oh, sorry, it's about Data model, of course

2020-12-04 08:22 UTC, asvishnyakov requested changes
All other changes is OK

2020-12-04 08:22 UTC, asvishnyakov commented on src/VirtoCommerce.DemoCustomerSegmentsModule.Data/Models/DemoCustomerSegmentEntity.cs
> +        public string UserGroup { get; set; }
[StringLength(64)]
https://github.com/VirtoCommerce/vc-module-customer/blob/ff7dd139fcbb8a9ead90c988d141d5dadec7cd0e/src/VirtoCommerce.CustomerModule.Data/Model/MemberGroupEntity.cs#L9

2020-12-04 09:17 UTC, ilyawzrd commented on src/VirtoCommerce.DemoCustomerSegmentsModule.Data/Models/DemoCustomerSegmentEntity.cs
> +        public string UserGroup { get; set; }
done

2020-12-04 09:22 UTC, trueboroda approved these changes

2020-12-04 13:23 UTC, pushnitsa submitted a review, later dismissed

2020-12-07 11:48 UTC, trueboroda approved these changes

2020-12-07 12:39 UTC, asvishnyakov approved these changes

2020-12-07 12:58 UTC, merged